spring:
    profiles:test
jdbc:
  mysql:
    host:10.139.36.81
    port:3306
    user:yuhancheng
    password:yuhancheng
    database:adtl_test

---
spring:
  profiles:prod
jdbc:
  mysql:
    host:adtd.datacenter.rds.sogou
    port:3306
    user:adtd
    password:noSafeNoWork2016
    database:datacenter