package models

var Dimension_Mapping = map[string]string{
	"CXC": "查询词",
	"YJQD":"一级渠道",
	"EJQD":"二级渠道",
	"PID":"PID",
	"WMQY":"网民区域",
	"RQ":"日期",
	"EJYWLX":"二级业务类型",
	"SJYWLX":"三级业务类型",
	"SD":"深度",
	"PV1":"PV1",
	"PV2":"PV2",
	"PV3":"PV3",
	"DJ":"点击",
	"XH":"消耗",
	"CXCHY_YIJI":"一级查询词行业",
	"CXCHY_ERJI":"二级查询词行业",
	"KHLX":"客户类型",
	"DLSID":"代理商ID",
	"DQ":"大区",
	"KHID":"客户ID",
	"YSLB":"样式类别",
	"YJKHHY":"一级客户行业",
	"EJKHHY":"二级客户行业",
	"SJKHHY":"三级客户行业",
	"JHID":"计划ID",
	"ZID":"组ID",
	"GJC":"关键词",
	"GJCID":"关键词ID",
	"KHMC":"客户名称",
	"JHMC":"计划名称",
	"ZMC":"组名称",
	"DLSMC":"代理商名称",
	"GGLX":"广告类型",
}
